name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - subdir: hijack
          - subdir: kot
          - subdir: koshka
          - subdir: planner
          - subdir: shin
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - run: mkdir bin

    #
    # The build won't run without this file
    #
    - run: touch planner/secret.json

    - name: Build ${{ matrix.subdir }}
      run: go build -v -o bin
      working-directory: ${{ matrix.subdir }}

    - name: Test ${{ matrix.subdir }}
      run: go test -v
      working-directory: ${{ matrix.subdir }}
